[versions]
#jetbrains
kotlin = "1.9.0"
kotlinxSerializationJson = "1.5.1"
ksp = "1.9.0-1.0.13"
room = "2.6.1"
material = "1.11.0"
#Simple tools
simple-commons = "37078b151c"
#Gradle
gradlePlugins-agp = "8.13.0"
#Other
indicatorFastScroll = "4524cd0b61"
autofitTextView = "0.2.1"
#build
app-build-compileSDKVersion = "34"
app-build-targetSDK = "34"
app-build-minimumSDK = "23"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
#versioning
app-version-appId = "com.simplemobiletools.dialer"
app-version-versionCode = "79" # update this for increment version in knox
app-version-versionName = "5.18.79"
[libraries]
#Simple Mobile Tools
simple-tools-commons = { module = "com.github.SimpleMobileTools:Simple-Commons", version.ref = "simple-commons" }
#Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
#Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
#Other
indicator-fast-scroll = { module = "com.github.tibbi:IndicatorFastScroll", version.ref = "indicatorFastScroll" }
autofit-text-view = { module = "me.grantland:autofittextview", version.ref = "autofitTextView" }
#Material
material = { module = "com.google.android.material:material", version.ref = "material" }
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
